### ISSUE TITLE
Majors list does not show

### ISSUE THREAD

**Issue by zacktraczyk** [SlugPath/SlugPath#274]
# Scope

When trying to change major or pick a major on homepage, the majors list seems to be empty.

![Image](https://github.com/SlugPath/SlugPath/assets/20495250/f556deb6-7e27-4972-a267-6a734ff5a925)

**Comment by fercevik729** [comment]
Majors won't show unless a catalog year is selected first, so maybe we can disable the majors dropdown until the catalog year is selected
