### ISSUE TITLE
Requirement List Notes Size & Spacing Issues

### ISSUE THREAD

**Issue by oluthje** [SlugPath/SlugPath#300]
1) The Requirement List notes size should set to be larger to fit the text on the rest of the page. Notes Editor should just have 1 size font for a consistent look on the page.
2) Notes Editor is not resized if there is little text on the screen. This should be fixed.

**Comment by zacktraczyk** [comment]
I made a fix for the planner notes at the bottom for the quill box, but not sure where the requirement list notes are, a screenshot of the boxes that need fixing or a description on how to get to them would be helpful.

**Comment by zacktraczyk** [comment]
> I made a fix for the planner notes at the bottom for the quill box, but not sure where the requirement list notes are, a screenshot of the boxes that need fixing or a description on how to get to them would be helpful.

I made this planner notes fix into a different PR.
