### ISSUE TITLE
Search Not Present in Replace Custom Course and Requirements Editing Modal

### ISSUE THREAD

**Issue by oluthje** [SlugPath/SlugPath#301]
![Image](https://github.com/SlugPath/SlugPath/assets/16377965/487d1ec8-fbf2-419c-b10d-31b38139cc62)

![Image](https://github.com/SlugPath/SlugPath/assets/16377965/8995f1ca-d1aa-495f-95cb-4cc0fb64149d)

Search does not display any courses, so users have difficulty replacing their courses.

**Comment by fercevik729** [comment]
This might have to do with how search is styled to fit the size of the container which it is in. It might be trivially fixed by increasing the height of the modal.

**Comment by zacktraczyk** [comment]
Yeh this is my fault. The component needs to be in a flexbox so it can expand to fill the modal. I am making a fix right now.

**Comment by zacktraczyk** [comment]
I fixed the custom course search modal but have been trying to trigger the Requirements editing Modal in the UI not sure where the button is.

**Comment by zacktraczyk** [comment]
Nvm found it, made a PR.
