### ISSUE TITLE
UI Suggestions

### ISSUE THREAD

**Issue by fercevik729** [SlugPath/SlugPath#312]
- [x] Rename graduation progress to something more relevant
- [x] Rename major progress to something more relevant
- [x] Bold year titles
- [x] New planner button should have some text
- [ ] Change course colors in light/dark theme
- [x] Add titles, tooltips, and headings as needed
- [ ] Better loading UI's

**Comment by lxu03** [comment]
I added tooltips instead of renaming graduation progress, major progress, and the add planner button
