### ISSUE TITLE
Course Availability Warnings Out of Date

### ISSUE THREAD

**Issue by cecilenoguera** [SlugPath/SlugPath#315]
In some cases, when selecting a course, a warning will appear stating that it is not offered in a specific quarter, but then it will show past and current offerings for that quarter. 

<img width="887" alt="Screenshot 2024-03-07 at 3 21 26 PM" src="https://github.com/SlugPath/SlugPath/assets/117109162/647da84f-41a0-4612-853f-2307dda59ab5">

**Comment by fercevik729** [comment]
I'm gonna go ahead and deprecate this feature because the way we fetch quarters is significantly different now and uses the PISA API directly rather than our DB. This has enabled us with more accurate quarter offering data that might change compared to the static data we had in our database
